# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d5961850a56c6a034cbe6c9b0a9528f35f4a591a21c6f328073f4c8a931edca8e588ede571911c9f232f5432caa1c606cb9cb8c7a90ceb20cac7a30145bde43

test:
  secret_key_base: cf5450f3dc787cd106ca52af6ba8615cf753b91ab438e5e731b94087ef47e121e4dd81e4ac2f5b3d1d3aae405e67d4f81100d8f6af6c5ef4a47afb4511587255

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
